### PR TITLE
Places

### PR DESCRIPTION
**Pull request by Alan-Turing13**
Now we can query google places for the following:
`landmarks`
`parks`
`wellness`

If the api key is present, places API will be called. 
If not, the local CSV files will be used instead.

The DTOs correspond to the 3 queries and they all inherit from an abstract class `Place` which has the following fields: name, openingHours, address and rating. As mentioned in daily stand-up, no image is being returned for now due to budget restraints.

### CODE REVIEW

**Comment by racheljayyx** [comment]
Looks good so far! When looking at the CSV there seem to be different opening times dependent on the day so how will it know which opening time to bring?

**Comment by Alan-Turing13** [comment]
@racheljayyx Ideally our frontend search will be for a specific day, so that we can separate the openingHours field into a list and select the day we want.

**Comment by racheljayyx** [comment]
@Alan-Turing13 that makes sense but how will the Google Places API know which date, as the controller only calls a type of activity not the date, unless I have misunderstood how your code works

**Comment by Alan-Turing13** [comment]
@racheljayyx No you haven't misunderstood - google places won't know which date, and you can't query it based on a date. This will be done in our global service layer.

**Comment by racheljayyx** [comment]
@Alan-Turing13 ah thanks that makes sense, thanks! I'm happy with your code! Looks really good

**Review by racheljayyx — APPROVED** [review]

**Pull request merged**
